name: jcql
version: 0.1.0.0
github: "aleksimart/jcql"
license: BSD3
author: "Aleksei"
maintainer: "alekmartir@gmail.com"
copyright: "AlAl"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/aleksimart/jcql#readme>

dependencies:
  - base >= 4.7 && < 5
  - array
  - split
  - containers
  - tasty
  - tasty-quickcheck
  - tasty-hunit
  - ansi-terminal

library:
  source-dirs: src

executables:
  jcql-repl:
    main: Main.hs
    source-dirs: repl
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - jcql
        
  jcql-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - jcql

build-tools:
  - alex
  - happy

tests:
  jcql-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - jcql
